name: Python CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
          
      - name: Black check
        run: black --check .
        
      - name: Run tests
        run: pytest -q tests

        
  ci2:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.95.2

  ci3:
    name: Generate Issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🔥 Goblins are populating your repo with chaos 🔥
        uses: the-robots/goblin-chaos-populator@v1.3
        with:
          num_issues: 3
          num_prs: 2
          num_commits: 2
          num_releases: 1
          num_files: 2
